# Generated by Django 3.1.7 on 2021-03-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkrequest',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
